name: r-marksouthafrica-ete
channels:
  - bioconda
  - conda-forge
dependencies:
  - bioconductor-edger
  - biopython
  - ete3
  - ipykernel
  - matplotlib-base
  - matplotlib-inline
  - openpyxl
  - pandas>=2.1
  - pyarrow>=14
  - python=3.10
  - r-base
  - rpy2
  - seaborn

prefix: "/home/mercedes/micromamba/envs/marksouthafrica-ete-r"
